apiVersion: v1
kind: Plugin
metadata:
  author: HwlloChen
  name: GoodNewsGenerator
  repository: 'https://github.com/HwlloChen/GoodNewsGenerator'
  version: 0.2.1
  description: 
    en_US: Plugin for generating good news and bad news images
    zh_Hans: 喜报/悲报生成器插件，根据关键词生成并发送喜报或悲报图片
  label:
    en_US: Good News Generator
    zh_Hans: 喜报/悲报生成器
spec:
  config:
    - name: font_path
      label:
        en_US: Custom Font Path
        zh_Hans: 自定义字体路径
      description:
        en_US: Optional custom font path for text rendering (not implemented yet, please change the font.ttf in the plugin directory)
        zh_Hans: 可选的自定义字体路径，用于文字渲染(暂未实现，请自行更改插件目录下的assets/font.ttf)
      type: string
      required: false
execution:
  python:
    path: main.py  # 插件主程序路径，必须与上方插件入口代码的文件名相同
    attr: GoodNewsGenerator  # 插件类名，必须与上方代码中声明的类名相同